[package]
name = "awaur"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Dependencies for feature "paginator"
futures-core = { version = "0.3", optional = true }
async-trait = { version = "0.1", optional = true }

[features]
default = [ "paginator" ]
paginator = [ "dep:futures-core", "dep:async-trait" ]
