[package]
name = "awaur"
version = "0.1.2"
authors = [ "Jacob Birkett <jacob@birkett.dev>" ]
edition = "2021"
description = "AWAUR: Asynchronous Web API Utilities for Rust"
repository = "https://github.com/spikespaz/awaur"
license = "MIT"
keywords = [ "web", "rest", "async", "api", "utilities" ]
categories = [ "rust-patterns", "web-programming", "asynchronous", "concurrency" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Dependencies for feature "paginator"
futures-core = { version = "0.3", optional = true }
async-trait = { version = "0.1", optional = true }

[features]
default = [ "paginator" ]
paginator = [ "dep:futures-core", "dep:async-trait" ]
